### PR TITLE
function amountOfDBIT added #10

### PR DESCRIPTION
**Pull request by Edoumou**
Cedric you can check it now

### CODE REVIEW

**Comment by toufic0710** [comment]
I think the bondExchangeRate is not a clear name, maybe it should be cdpDBIT or usdToDbitToMint. 

conversionTokenToDbit seems redondant, did you meant conversionTokenToUsd? anyway, you need to take the token address as a param. The core of the function is left for later for when we have the oracle, as you did.

Let's begin by fixing this and then we will see last function.

Maybe it could look like this : 


`function USDToDbitToMint(uint DBITtotalSupply) public  returns (uint amount_dbit) {`
        `if (_dbitTotalSupply < 1e5) {`
                   ` amount_dbit = 1 ether;`
        `} else {`
             `  uint256 logTotalSupply = SafeMath.ln(DBITtotalSupply * 1e13);`
             `amount_dbit = SafeMath.pow(1.05 * 1 ether, logTotalSupply);`
`}`

`function convertTokenToUsd(uint256 _amountToken, address tokenAddress) internal pure returns(uint256 amountUsd) {`
         `// This must be done later when the oracle will be implemented`
         ` amountUsd = _amountToken;`
   `}`
        
For last function : 

`function amountOfDBITToMint(uint256 _amountToken, address tokenAddress, uint256 _dbitTotalSupply) external pure returns(uint256 amountDBIT) { `
        ` require(_amountToken > 0, "Debond: Provide some tokens");`
        `uint256 tokenToUsd = convertTokenToUsd(_amountToken, tokenAddress)`
        `uint256 priceFor1Usd = USDToDbitToMint(_dbitTotalSupply)`
       `amountDBIT = tokenToUsd * priceFor1Usd;` 
    `}`
       
So the logic is the same as you, just updated some function name and some variables.

**Comment by Edoumou** [comment]
Hello @toufic0710 

I didn't create the CDP contract, you probably created it. So, all functions names and so on can be changed by who has created the contract. Yesterday, I just added some functions for @drikssy  to be able to get what he wanted.

So, if you are the one who created that contract you can make all changes you wish, and once finished PR for review

**Comment by GrandGarcon** [comment]
ah actually its me who created that , so indeed if you wish some changes to be integrated i will add them via another PR .

**Comment by drikssy** [comment]
I close the PR as it is finally not needed guys thanks @Edoumou @toufic0710  @toufic0710 :+1:

**Pull request closed without merging**
